apiVersion: v1
kind: Secret
metadata:
  name: ev-predictor-secret
  namespace: ev-predictor
type: Opaque
data:
  # "user" -> base64 encoded
  DATABASE_USER: postgres
  # "password" -> base64 encoded
  DATABASE_PASSWORD: dunith